export { default as App } from "./app/app.component";
export { default as Header } from "./header/header.component";
export { default as Select } from "./select/select.component";
export { default as Cities } from "./cities/cities.component";
export { default as Snake } from "./snake/snake.component";
export { default as List } from "./list/list.component";
export { default as Item } from "./item/item.component";
export { default as People } from "./people/people.component";
export { default as LanguageImitation } from "./language-imitation/language-imitation.component";
